# Generated by Django 4.2.15 on 2024-09-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image_path',
            field=models.ImageField(max_length=255, upload_to='post_images/'),
        ),
    ]
